/**
 * Message persistence helpers.
 */

import { ConversationRepository } from '@/server/repositories/conversation.repository'
import { MessageRepository } from '@/server/repositories/message.repository'
import type { ToolCall } from '@/server/services/tools'

export interface ToolResultData {
  toolCallId: string
  name: string
  result: Record<string, unknown>
}

export interface MessageContent {
  thinkingContent: string
  answerContent: string
  toolCallsData: ToolCall[] | null
  toolResultsData?: ToolResultData[] | null
}

export async function persistMessage(
  messageId: string,
  conversationId: string,
  userId: string,
  content: MessageContent
): Promise<void> {
  try {
    await MessageRepository.update(messageId, {
      content: content.answerContent,
      thinking: content.thinkingContent || undefined,
      toolCalls: content.toolCallsData
        ? (JSON.parse(JSON.stringify(content.toolCallsData)) as object)
        : undefined,
      toolResults: content.toolResultsData
        ? (JSON.parse(JSON.stringify(content.toolResultsData)) as object)
        : undefined,
    })

    await ConversationRepository.touch(conversationId, userId)
  } catch (error) {
    console.error('[MessagePersister] Failed to save message:', error)
  }
}

export function processImageResults(
  answerContent: string,
  allToolCalls: ToolCall[],
  allToolResults: Array<{ toolCallId: string; name: string; result: Record<string, unknown> }>
): string {
  let contentWithImages = answerContent.replace(/```image\n[\s\S]*?```\n?/g, '')

  // Remove fake image links generated by model text.
  contentWithImages = contentWithImages.replace(
    /\[[^\]]*?(图片|查看|下载|生成)[^\]]*?\]\([^)]*\)/gi,
    ''
  )
  contentWithImages = contentWithImages.replace(/!\[[^\]]*\]\([^)]+\)/g, '')
  contentWithImages = contentWithImages.replace(/点击查看.*?图片/gi, '')
  contentWithImages = contentWithImages.replace(/\n{3,}/g, '\n\n').trim()

  for (const toolResult of allToolResults) {
    const imageUrl = getImageUrl(toolResult.result)
    if (toolResult.name !== 'generate_image' || !imageUrl) {
      continue
    }

    const width = toPositiveNumber(toolResult.result.width) || 512
    const height = toPositiveNumber(toolResult.result.height) || 512
    const prompt = extractPromptFromToolCall(allToolCalls, toolResult.toolCallId) || 'Generated image'

    const imageData = JSON.stringify({
      url: imageUrl,
      alt: prompt,
      width,
      height,
    })
    contentWithImages += `\n\`\`\`image\n${imageData}\n\`\`\`\n`
  }

  return contentWithImages
}

function extractPromptFromToolCall(
  toolCalls: ToolCall[],
  toolCallId: string
): string | undefined {
  const matchedToolCall = toolCalls.find((call) => call.id === toolCallId)
  if (!matchedToolCall) return undefined

  try {
    const parsedArgs = JSON.parse(matchedToolCall.function.arguments)
    return typeof parsedArgs.prompt === 'string' && parsedArgs.prompt.length > 0
      ? parsedArgs.prompt
      : undefined
  } catch {
    return undefined
  }
}

function getImageUrl(result: Record<string, unknown>): string | undefined {
  const imageUrl = result.imageUrl
  if (typeof imageUrl === 'string' && imageUrl.length > 0) {
    return imageUrl
  }

  const url = result.url
  if (typeof url === 'string' && url.length > 0) {
    return url
  }

  return undefined
}

function toPositiveNumber(value: unknown): number | undefined {
  if (typeof value !== 'number' || !Number.isFinite(value)) {
    return undefined
  }
  if (value <= 0) {
    return undefined
  }
  return value
}
